#!/bin/bash
#
# Download and setup Xilinx sources as per instruction from Xilinx and the
# README in this repo.
#

error() {
    echo "ERROR: $1"
    exit 1
}

CMD=$(readlink -f "$0")
LAYER_DIR=$(dirname "$CMD")
PROJECT_DIR=meta-iveia-project

[ "$LAYER_DIR" != "$PWD" ] || error "Cannot run from within the meta-iveia layer directory"
[ $(basename "$LAYER_DIR") = meta-iveia ] || error "layer dir must be named meta-iveia"
mkdir "$PROJECT_DIR" || error "\"$PROJECT_DIR\" must not already exist"

cd "$PROJECT_DIR" || error "cd failed"
repo init -u git://github.com/Xilinx/yocto-manifests.git -b rel-v2019.2 || error "repo init failed"
repo sync || error "repo sync failed"
mv "$LAYER_DIR" sources || error "mv failed"
source setupsdk || error "source setupsdk failed"
bitbake-layers add-layer ../sources/meta-iveia || error "bitbake-layers failed"
