#!/bin/bash
#
# Download and setup Xilinx sources as per instruction from Xilinx and the
# README in this repo.
#

error() {
    echo "ERROR: $1"
    exit 1
}

CMD=$(readlink -f "$0")
LAYER_DIR=$(dirname "$CMD")
LAYER_NAME=meta-iveia
PROJECT_DIR="${LAYER_NAME}-project"

if [ "$1" == DONTMOVELAYER ]; then
    MOVELAYER=0
    LAYER_FINAL_DIR=..
else
    MOVELAYER=1
    LAYER_FINAL_DIR=sources
fi
# Clear all positional args (REQUIRED for later "source" command)
shift $#

[ "$LAYER_DIR" != "$PWD" ] || error "Cannot run from within the $LAYER_NAME layer directory"
[ $(basename "$LAYER_DIR") = "$LAYER_NAME" ] || error "layer dir must be named $LAYER_NAME"
mkdir "$PROJECT_DIR" || error "\"$PROJECT_DIR\" must not already exist"

cd "$PROJECT_DIR" || error "cd failed"
repo init -u git://github.com/Xilinx/yocto-manifests.git -b rel-v2021.2 || error "repo init failed"
repo sync || error "repo sync failed"
((MOVELAYER)) && (mv "$LAYER_DIR" "$LAYER_FINAL_DIR" || error "mv failed")
source setupsdk || error "source setupsdk failed"
bitbake-layers add-layer "../$LAYER_FINAL_DIR/$LAYER_NAME" || error "bitbake-layers failed"
